# Generated by Django 5.2 on 2025-05-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='thumbnail',
        ),
    ]
