# Generated by Django 5.2 on 2025-05-15 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='coordsx',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='coordsy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='z',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='buildtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='showcase.tag'),
        ),
    ]
