# Generated by Django 5.2 on 2025-05-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_build_coordsx_build_coordsy_build_z_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='z',
            new_name='coordsz',
        ),
    ]
