# Generated by Django 5.2 on 2025-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_alter_image_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='default'),
            preserve_default=False,
        ),
    ]
