# Generated by Django 5.2 on 2025-05-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_rename_z_build_coordsz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='coordsx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='coordsy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='coordsz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
