# Generated by Django 5.2 on 2025-05-24 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_alter_build_thumbnail_alter_image_build_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thumbnail', to='showcase.image'),
        ),
    ]
