# Generated by Django 5.2 on 2025-05-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_build_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Thumbnail', to='showcase.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='showcase.build'),
        ),
    ]
