# Generated by Django 5.2 on 2025-05-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_alter_build_thumbnail_alter_image_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Thumbnail', to='showcase.image'),
        ),
    ]
