# Generated by Django 5.2 on 2025-05-25 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_alter_build_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='build',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='showcase.build'),
            preserve_default=False,
        ),
    ]
